import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "your-email@gmail.com"
SENDER_PASSWORD = "your-app-password"

def send_email_report(recipient_email, subject, body, attachment_path=None):
    try:
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = recipient_email
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'html'))
        
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    'Content-Disposition',
                    f'attachment; filename= {os.path.basename(attachment_path)}'
                )
                msg.attach(part)
        
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        
        return True
    except Exception as e:
        print(f"Email sending error: {str(e)}")
        return False

def generate_email_body(analysis_data):
    label = analysis_data.get('label', 'N/A')
    confidence = analysis_data.get('confidence', 0)
    food_type = analysis_data.get('food_type', 'N/A')
    timestamp = analysis_data.get('timestamp', 'N/A')
    
    color = '#4CAF50' if label == 'Fresh' else '#FF9800' if label == 'Okay' else '#f44336'
    
    html = f"""
    <html>
        <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f5f5f5;">
            <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 10px; padding: 30px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                <h1 style="color: {color}; text-align: center;">Food Freshness Analysis Report</h1>
                <hr style="border: 1px solid #e0e0e0;">
                
                <h2 style="color: #333;">Analysis Results</h2>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <td style="padding: 10px; background: #f9f9f9; font-weight: bold;">Result:</td>
                        <td style="padding: 10px; color: {color}; font-weight: bold;">{label}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; background: #f9f9f9; font-weight: bold;">Confidence:</td>
                        <td style="padding: 10px;">{confidence}%</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; background: #f9f9f9; font-weight: bold;">Food Type:</td>
                        <td style="padding: 10px;">{food_type.title()}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; background: #f9f9f9; font-weight: bold;">Date:</td>
                        <td style="padding: 10px;">{timestamp}</td>
                    </tr>
                </table>
                
                <div style="margin-top: 30px; padding: 20px; background: #e8f5e9; border-radius: 5px;">
                    <h3 style="color: #2e7d32; margin-top: 0;">Storage Tips</h3>
                    <p style="color: #555; line-height: 1.6;">
                        Please refer to the attached PDF report for detailed storage recommendations and tips.
                    </p>
                </div>
                
                <div style="margin-top: 30px; text-align: center; color: #999; font-size: 12px;">
                    <p>Generated by Food Freshness Classifier</p>
                    <p>&copy; 2024 All rights reserved</p>
                </div>
            </div>
        </body>
    </html>
    """
    
    return html
