from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import qrcode
import io
import os

def generate_pdf_report(analysis_data, output_path):
    try:
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#4CAF50'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        title = Paragraph("Food Freshness Analysis Report", title_style)
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        info_data = [
            ['Analysis Date:', analysis_data.get('timestamp', 'N/A')],
            ['Result:', analysis_data.get('label', 'N/A')],
            ['Confidence:', f"{analysis_data.get('confidence', 0)}%"],
            ['Food Type:', analysis_data.get('food_type', 'N/A').title()],
            ['Image Quality:', analysis_data.get('quality', {}).get('quality', 'N/A')],
            ['Resolution:', analysis_data.get('quality', {}).get('resolution', 'N/A')],
        ]
        
        info_table = Table(info_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        
        story.append(info_table)
        story.append(Spacer(1, 0.3*inch))
        
        if analysis_data.get('image_path') and os.path.exists(analysis_data['image_path']):
            img = RLImage(analysis_data['image_path'], width=4*inch, height=3*inch)
            story.append(img)
            story.append(Spacer(1, 0.2*inch))
        
        storage_tips = analysis_data.get('storage_tips', {})
        if storage_tips:
            tips_title = Paragraph("<b>Storage Recommendations:</b>", styles['Heading2'])
            story.append(tips_title)
            story.append(Spacer(1, 0.1*inch))
            
            tips_data = [
                ['Temperature:', storage_tips.get('temperature', 'N/A')],
                ['Humidity:', storage_tips.get('humidity', 'N/A')],
                ['Shelf Life:', storage_tips.get('shelf_life', 'N/A')],
            ]
            
            tips_table = Table(tips_data, colWidths=[2*inch, 4*inch])
            tips_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5e9')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            
            story.append(tips_table)
        
        qr = qrcode.QRCode(version=1, box_size=3, border=2)
        qr.add_data(f"Analysis ID: {analysis_data.get('id', 'N/A')}")
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white")
        
        qr_buffer = io.BytesIO()
        qr_img.save(qr_buffer, format='PNG')
        qr_buffer.seek(0)
        
        story.append(Spacer(1, 0.3*inch))
        qr_image = RLImage(qr_buffer, width=1.5*inch, height=1.5*inch)
        story.append(qr_image)
        
        footer = Paragraph(
            f"<i>Generated by Food Freshness Classifier - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>",
            styles['Normal']
        )
        story.append(Spacer(1, 0.2*inch))
        story.append(footer)
        
        doc.build(story)
        return True
    except Exception as e:
        print(f"PDF generation error: {str(e)}")
        return False
